package org.examples.time_manager.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val DarkColorScheme = darkColorScheme(
    primary = Color(0xFF333333),
    secondary = Color(0xFFcec6b2),
    tertiary = Color(0xFFffffff),
    onPrimary = Color(0xFFFFFFFF),
    onSecondary = Color(0xFF343022),
    onTertiary = Color(0xFF2c331a),
    primaryContainer = Color(0xFFe1d4aa),
    secondaryContainer = Color(0xFF413d2e),
    tertiaryContainer = Color(0xFFd0d9b4),
    onPrimaryContainer = Color(0xFF473f20),
    onSecondaryContainer = Color(0xFFd8d0bc),
    onTertiaryContainer = Color(0xFF3a4228),
    surfaceDim = Color(0xFF141310),
    surface = Color(0xFF141310),
    surfaceBright = Color(0xFF3b3936),
    surfaceContainerLowest = Color(0xFF0f0e0b),
    surfaceContainerLow = Color(0xFF1d1b18),
    surfaceContainer = Color(0xFF211f1c),
    surfaceContainerHigh = Color(0xFF2b2a27),
    surfaceContainerHighest = Color(0xFF363431),
    onSurface = Color(0xFFe7e2dd),
    onSurfaceVariant = Color(0xFFccc6b8),
    outline = Color(0xFF969084),
    outlineVariant = Color(0xFF4a473c),
    error = Color(0xFFffb4ab),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000a),
    onErrorContainer = Color(0xFF93000a),
    inverseSurface = Color(0xFFe7e2dd),
    inverseOnSurface = Color(0xFF32302d),
    inversePrimary = Color(0xFF675e3c),
    scrim = Color(0xFF000000),
)

val LightColorScheme = lightColorScheme(
    primary = Color(0xFF675e3c),
    secondary = Color(0xFF635e4e),
    tertiary = Color(0xFF596244),
    onPrimary = Color(0xFFffffff),
    onSecondary = Color(0xFFffffff),
    onTertiary = Color(0xFFffffff),
    primaryContainer = Color(0xFFfff2cb),
    secondaryContainer = Color(0xFFC9BEA1),
    tertiaryContainer = Color(0xFFeef7d1),
    onPrimaryContainer = Color(0xFF1D1D1D),
    onSecondaryContainer = Color(0xFF573333),
    onTertiaryContainer = Color(0xFF5A5050),
    surfaceDim = Color(0xFFe7e2dd),
    surface = Color(0xFFe7e2dd),
    surfaceBright = Color(0xFFe7e2dd),
    surfaceContainerLowest = Color(0xFFe7e2dd),
    surfaceContainerLow = Color(0xFFe7e2dd),
    surfaceContainer = Color(0xFFe7e2dd),
    surfaceContainerHigh = Color(0xFFe7e2dd),
    surfaceContainerHighest = Color(0xFFe7e2dd),
    onSurface = Color(0xFF1d1b18),
    onSurfaceVariant = Color(0xFF4a473c),
    outline = Color(0xFF7b776b),
    outlineVariant = Color(0xFFccc6b8),
    error = Color(0xFFba1a1a),
    onError = Color(0xFFffffff),
    errorContainer = Color(0xFFffdad6),
    onErrorContainer = Color(0xFF410002),
    inverseSurface = Color(0xFF32302d),
    inverseOnSurface = Color(0xFFf5f0eb),
    inversePrimary = Color(0xFFd3c69d),
    scrim = Color(0xFF000000),
)
